/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentProbeConfigsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentProbeConfigsResponse{}

// AgentProbeConfigsResponse The probes in effect, with every field resolved.
type AgentProbeConfigsResponse struct {
	Startup   AgentProbeConfig `json:"startup"`
	Readiness AgentProbeConfig `json:"readiness"`
	Liveness  AgentProbeConfig `json:"liveness"`
	// True when the agent's current deployment in this environment predates configurable probes. Probe settings are saved but take effect only after the agent is deployed again.
	RedeployRequired bool `json:"redeployRequired"`
}

// NewAgentProbeConfigsResponse instantiates a new AgentProbeConfigsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentProbeConfigsResponse(startup AgentProbeConfig, readiness AgentProbeConfig, liveness AgentProbeConfig, redeployRequired bool) *AgentProbeConfigsResponse {
	this := AgentProbeConfigsResponse{}
	this.Startup = startup
	this.Readiness = readiness
	this.Liveness = liveness
	this.RedeployRequired = redeployRequired
	return &this
}

// NewAgentProbeConfigsResponseWithDefaults instantiates a new AgentProbeConfigsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentProbeConfigsResponseWithDefaults() *AgentProbeConfigsResponse {
	this := AgentProbeConfigsResponse{}
	return &this
}

// GetStartup returns the Startup field value
func (o *AgentProbeConfigsResponse) GetStartup() AgentProbeConfig {
	if o == nil {
		var ret AgentProbeConfig
		return ret
	}

	return o.Startup
}

// GetStartupOk returns a tuple with the Startup field value
// and a boolean to check if the value has been set.
func (o *AgentProbeConfigsResponse) GetStartupOk() (*AgentProbeConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Startup, true
}

// SetStartup sets field value
func (o *AgentProbeConfigsResponse) SetStartup(v AgentProbeConfig) {
	o.Startup = v
}

// GetReadiness returns the Readiness field value
func (o *AgentProbeConfigsResponse) GetReadiness() AgentProbeConfig {
	if o == nil {
		var ret AgentProbeConfig
		return ret
	}

	return o.Readiness
}

// GetReadinessOk returns a tuple with the Readiness field value
// and a boolean to check if the value has been set.
func (o *AgentProbeConfigsResponse) GetReadinessOk() (*AgentProbeConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Readiness, true
}

// SetReadiness sets field value
func (o *AgentProbeConfigsResponse) SetReadiness(v AgentProbeConfig) {
	o.Readiness = v
}

// GetLiveness returns the Liveness field value
func (o *AgentProbeConfigsResponse) GetLiveness() AgentProbeConfig {
	if o == nil {
		var ret AgentProbeConfig
		return ret
	}

	return o.Liveness
}

// GetLivenessOk returns a tuple with the Liveness field value
// and a boolean to check if the value has been set.
func (o *AgentProbeConfigsResponse) GetLivenessOk() (*AgentProbeConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Liveness, true
}

// SetLiveness sets field value
func (o *AgentProbeConfigsResponse) SetLiveness(v AgentProbeConfig) {
	o.Liveness = v
}

// GetRedeployRequired returns the RedeployRequired field value
func (o *AgentProbeConfigsResponse) GetRedeployRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RedeployRequired
}

// GetRedeployRequiredOk returns a tuple with the RedeployRequired field value
// and a boolean to check if the value has been set.
func (o *AgentProbeConfigsResponse) GetRedeployRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedeployRequired, true
}

// SetRedeployRequired sets field value
func (o *AgentProbeConfigsResponse) SetRedeployRequired(v bool) {
	o.RedeployRequired = v
}

func (o AgentProbeConfigsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentProbeConfigsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["startup"] = o.Startup
	toSerialize["readiness"] = o.Readiness
	toSerialize["liveness"] = o.Liveness
	toSerialize["redeployRequired"] = o.RedeployRequired
	return toSerialize, nil
}

type NullableAgentProbeConfigsResponse struct {
	value *AgentProbeConfigsResponse
	isSet bool
}

func (v NullableAgentProbeConfigsResponse) Get() *AgentProbeConfigsResponse {
	return v.value
}

func (v *NullableAgentProbeConfigsResponse) Set(val *AgentProbeConfigsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentProbeConfigsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentProbeConfigsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentProbeConfigsResponse(val *AgentProbeConfigsResponse) *NullableAgentProbeConfigsResponse {
	return &NullableAgentProbeConfigsResponse{value: val, isSet: true}
}

func (v NullableAgentProbeConfigsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentProbeConfigsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
