/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the UpdateAgentProbeConfigsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAgentProbeConfigsRequest{}

// UpdateAgentProbeConfigsRequest Probes to change. Omitted probes and fields are left as they are.
type UpdateAgentProbeConfigsRequest struct {
	Startup   *AgentProbeConfig `json:"startup,omitempty"`
	Readiness *AgentProbeConfig `json:"readiness,omitempty"`
	Liveness  *AgentProbeConfig `json:"liveness,omitempty"`
}

// NewUpdateAgentProbeConfigsRequest instantiates a new UpdateAgentProbeConfigsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAgentProbeConfigsRequest() *UpdateAgentProbeConfigsRequest {
	this := UpdateAgentProbeConfigsRequest{}
	return &this
}

// NewUpdateAgentProbeConfigsRequestWithDefaults instantiates a new UpdateAgentProbeConfigsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAgentProbeConfigsRequestWithDefaults() *UpdateAgentProbeConfigsRequest {
	this := UpdateAgentProbeConfigsRequest{}
	return &this
}

// GetStartup returns the Startup field value if set, zero value otherwise.
func (o *UpdateAgentProbeConfigsRequest) GetStartup() AgentProbeConfig {
	if o == nil || IsNil(o.Startup) {
		var ret AgentProbeConfig
		return ret
	}
	return *o.Startup
}

// GetStartupOk returns a tuple with the Startup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentProbeConfigsRequest) GetStartupOk() (*AgentProbeConfig, bool) {
	if o == nil || IsNil(o.Startup) {
		return nil, false
	}
	return o.Startup, true
}

// HasStartup returns a boolean if a field has been set.
func (o *UpdateAgentProbeConfigsRequest) HasStartup() bool {
	if o != nil && !IsNil(o.Startup) {
		return true
	}

	return false
}

// SetStartup gets a reference to the given AgentProbeConfig and assigns it to the Startup field.
func (o *UpdateAgentProbeConfigsRequest) SetStartup(v AgentProbeConfig) {
	o.Startup = &v
}

// GetReadiness returns the Readiness field value if set, zero value otherwise.
func (o *UpdateAgentProbeConfigsRequest) GetReadiness() AgentProbeConfig {
	if o == nil || IsNil(o.Readiness) {
		var ret AgentProbeConfig
		return ret
	}
	return *o.Readiness
}

// GetReadinessOk returns a tuple with the Readiness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentProbeConfigsRequest) GetReadinessOk() (*AgentProbeConfig, bool) {
	if o == nil || IsNil(o.Readiness) {
		return nil, false
	}
	return o.Readiness, true
}

// HasReadiness returns a boolean if a field has been set.
func (o *UpdateAgentProbeConfigsRequest) HasReadiness() bool {
	if o != nil && !IsNil(o.Readiness) {
		return true
	}

	return false
}

// SetReadiness gets a reference to the given AgentProbeConfig and assigns it to the Readiness field.
func (o *UpdateAgentProbeConfigsRequest) SetReadiness(v AgentProbeConfig) {
	o.Readiness = &v
}

// GetLiveness returns the Liveness field value if set, zero value otherwise.
func (o *UpdateAgentProbeConfigsRequest) GetLiveness() AgentProbeConfig {
	if o == nil || IsNil(o.Liveness) {
		var ret AgentProbeConfig
		return ret
	}
	return *o.Liveness
}

// GetLivenessOk returns a tuple with the Liveness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAgentProbeConfigsRequest) GetLivenessOk() (*AgentProbeConfig, bool) {
	if o == nil || IsNil(o.Liveness) {
		return nil, false
	}
	return o.Liveness, true
}

// HasLiveness returns a boolean if a field has been set.
func (o *UpdateAgentProbeConfigsRequest) HasLiveness() bool {
	if o != nil && !IsNil(o.Liveness) {
		return true
	}

	return false
}

// SetLiveness gets a reference to the given AgentProbeConfig and assigns it to the Liveness field.
func (o *UpdateAgentProbeConfigsRequest) SetLiveness(v AgentProbeConfig) {
	o.Liveness = &v
}

func (o UpdateAgentProbeConfigsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAgentProbeConfigsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Startup) {
		toSerialize["startup"] = o.Startup
	}
	if !IsNil(o.Readiness) {
		toSerialize["readiness"] = o.Readiness
	}
	if !IsNil(o.Liveness) {
		toSerialize["liveness"] = o.Liveness
	}
	return toSerialize, nil
}

type NullableUpdateAgentProbeConfigsRequest struct {
	value *UpdateAgentProbeConfigsRequest
	isSet bool
}

func (v NullableUpdateAgentProbeConfigsRequest) Get() *UpdateAgentProbeConfigsRequest {
	return v.value
}

func (v *NullableUpdateAgentProbeConfigsRequest) Set(val *UpdateAgentProbeConfigsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAgentProbeConfigsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAgentProbeConfigsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAgentProbeConfigsRequest(val *UpdateAgentProbeConfigsRequest) *NullableUpdateAgentProbeConfigsRequest {
	return &NullableUpdateAgentProbeConfigsRequest{value: val, isSet: true}
}

func (v NullableUpdateAgentProbeConfigsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAgentProbeConfigsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
