/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentHealthChecks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentHealthChecks{}

// AgentHealthChecks The agent's health checks. Set at build time because they depend on the agent image; they apply to every environment from the next deploy, and their wait times are the baseline an environment may override. In a request, omitted fields keep their current values (platform defaults for a new agent). In a configurations response, the checks in effect for that environment.
type AgentHealthChecks struct {
	// Port the checks run against. Defaults to the agent's port.
	Port      *int32            `json:"port,omitempty"`
	Startup   *AgentHealthCheck `json:"startup,omitempty"`
	Readiness *AgentHealthCheck `json:"readiness,omitempty"`
	Liveness  *AgentHealthCheck `json:"liveness,omitempty"`
}

// NewAgentHealthChecks instantiates a new AgentHealthChecks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentHealthChecks() *AgentHealthChecks {
	this := AgentHealthChecks{}
	return &this
}

// NewAgentHealthChecksWithDefaults instantiates a new AgentHealthChecks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentHealthChecksWithDefaults() *AgentHealthChecks {
	this := AgentHealthChecks{}
	return &this
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *AgentHealthChecks) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHealthChecks) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *AgentHealthChecks) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *AgentHealthChecks) SetPort(v int32) {
	o.Port = &v
}

// GetStartup returns the Startup field value if set, zero value otherwise.
func (o *AgentHealthChecks) GetStartup() AgentHealthCheck {
	if o == nil || IsNil(o.Startup) {
		var ret AgentHealthCheck
		return ret
	}
	return *o.Startup
}

// GetStartupOk returns a tuple with the Startup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHealthChecks) GetStartupOk() (*AgentHealthCheck, bool) {
	if o == nil || IsNil(o.Startup) {
		return nil, false
	}
	return o.Startup, true
}

// HasStartup returns a boolean if a field has been set.
func (o *AgentHealthChecks) HasStartup() bool {
	if o != nil && !IsNil(o.Startup) {
		return true
	}

	return false
}

// SetStartup gets a reference to the given AgentHealthCheck and assigns it to the Startup field.
func (o *AgentHealthChecks) SetStartup(v AgentHealthCheck) {
	o.Startup = &v
}

// GetReadiness returns the Readiness field value if set, zero value otherwise.
func (o *AgentHealthChecks) GetReadiness() AgentHealthCheck {
	if o == nil || IsNil(o.Readiness) {
		var ret AgentHealthCheck
		return ret
	}
	return *o.Readiness
}

// GetReadinessOk returns a tuple with the Readiness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHealthChecks) GetReadinessOk() (*AgentHealthCheck, bool) {
	if o == nil || IsNil(o.Readiness) {
		return nil, false
	}
	return o.Readiness, true
}

// HasReadiness returns a boolean if a field has been set.
func (o *AgentHealthChecks) HasReadiness() bool {
	if o != nil && !IsNil(o.Readiness) {
		return true
	}

	return false
}

// SetReadiness gets a reference to the given AgentHealthCheck and assigns it to the Readiness field.
func (o *AgentHealthChecks) SetReadiness(v AgentHealthCheck) {
	o.Readiness = &v
}

// GetLiveness returns the Liveness field value if set, zero value otherwise.
func (o *AgentHealthChecks) GetLiveness() AgentHealthCheck {
	if o == nil || IsNil(o.Liveness) {
		var ret AgentHealthCheck
		return ret
	}
	return *o.Liveness
}

// GetLivenessOk returns a tuple with the Liveness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHealthChecks) GetLivenessOk() (*AgentHealthCheck, bool) {
	if o == nil || IsNil(o.Liveness) {
		return nil, false
	}
	return o.Liveness, true
}

// HasLiveness returns a boolean if a field has been set.
func (o *AgentHealthChecks) HasLiveness() bool {
	if o != nil && !IsNil(o.Liveness) {
		return true
	}

	return false
}

// SetLiveness gets a reference to the given AgentHealthCheck and assigns it to the Liveness field.
func (o *AgentHealthChecks) SetLiveness(v AgentHealthCheck) {
	o.Liveness = &v
}

func (o AgentHealthChecks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentHealthChecks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Startup) {
		toSerialize["startup"] = o.Startup
	}
	if !IsNil(o.Readiness) {
		toSerialize["readiness"] = o.Readiness
	}
	if !IsNil(o.Liveness) {
		toSerialize["liveness"] = o.Liveness
	}
	return toSerialize, nil
}

type NullableAgentHealthChecks struct {
	value *AgentHealthChecks
	isSet bool
}

func (v NullableAgentHealthChecks) Get() *AgentHealthChecks {
	return v.value
}

func (v *NullableAgentHealthChecks) Set(val *AgentHealthChecks) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentHealthChecks) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentHealthChecks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentHealthChecks(val *AgentHealthChecks) *NullableAgentHealthChecks {
	return &NullableAgentHealthChecks{value: val, isSet: true}
}

func (v NullableAgentHealthChecks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentHealthChecks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
